# Generated by Django 4.0.5 on 2022-06-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bs_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
